version: '3.8'

# https://github.com/emqx/emqx?tab=readme-ov-file#run-emqx-using-docker

services:
  mqtt-server:
    image: emqx/emqx:latest
    container_name: mqtt-server
    ports:
      - "8083:8083"
      - "18083:18083" # Web-UI, Default-Login: admin/public
    restart: always  # Optional: ensures the container restarts on failure
  mqtt-sender:
    build:
      context: 1_Sender
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mqtt-server
  mqtt-empfaenger:
    build:
      context: 2_Empfaenger
      dockerfile: Dockerfile
    depends_on:
      - mqtt-sender
